[package]
name = "zj-status-bar"
version = "0.2.0"
authors = ["Cristian Dominguez", "Alexander Kenji Berthold <aks.kenji@protonmail.com>" ]
edition = "2021"
license = "MIT"

[dependencies]
ansi_term = "0.12"
unicode-width = "0.1.8"
zellij-tile = "0.40.0"
zellij-tile-utils = "0.40.0"
